### ISSUE TITLE
AttributeError: 'list' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by gauravkuppa** [BGU-CS-VIL/dtan#5]
After training the model, I get this error in the plotting the outputs. 

```
Traceback (most recent call last):
  File "UCR_alignment.py", line 111, in <module>
    run_UCR_alignment(args)
  File "UCR_alignment.py", line 104, in run_UCR_alignment
    DTAN.plot_RDTAN_outputs(model, X_train, y_train, ratio=[6,4])
  File "/home/dtan/DTAN/DTAN_layer.py", line 123, in plot_RDTAN_outputs
    plot_all_layers(model, X, y, self.n_recurrences, ratio)
  File "/home/dtan/helper/plot_transformer_layer.py", line 33, in plot_all_layers
    X_within_class_aligned = curr_layer([X_within_class])
  File "/home/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2961, in __call__
    tensor_type = dtypes_module.as_dtype(tensor.dtype)
AttributeError: 'list' object has no attribute 'dtype'
```
If I remove the [] around X_within_class, I get another error:

```
Traceback (most recent call last):
  File "UCR_alignment.py", line 111, in <module>
    run_UCR_alignment(args)
  File "UCR_alignment.py", line 104, in run_UCR_alignment
    DTAN.plot_RDTAN_outputs(model, X_train, y_train, ratio=[6,4])
  File "/home/dtan/DTAN/DTAN_layer.py", line 123, in plot_RDTAN_outputs
    plot_all_layers(model, X, y, self.n_recurrences, ratio)
  File "/home/dtan/helper/plot_transformer_layer.py", line 33, in plot_all_layers
    X_within_class_aligned = curr_layer(X_within_class)
  File "/home/dtan/venv_dtan/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2937, in __call__
    raise TypeError('`inputs` should be a list or tuple.')
TypeError: `inputs` should be a list or tuple.
```

Is there a better way to plot results of the alignment?

**Comment by gauravkuppa** [comment]
how can i create a PR? i found a way to fix it

**Comment by ronshapiraweber** [comment]
Happy to hear it! 
There's a 'Pull request' tab right next to the 'Issues' one.

If you are having troubles, feel free to email me.

**Comment by gauravkuppa** [comment]
Yeah, I saw that. I am just not able to create a new branch and push it because I don't have permissions to the repo.

**Comment by ronshapiraweber** [comment]
Try Forking the repo, apply the fix, and then create a pull request from the forked version to the master branch.

**Comment by ronshapiraweber** [comment]
Closing this issue, please let me know if you managed to fork + pull request. 
Feel free to reach me on email.
